//
//  MessagesViewController.m
//  MessagesExtension
//
//  Created by 이재성 on 09/11/2016.
//  Copyright © 2016 HUB. All rights reserved.
//

#import "MessagesViewController.h"



@interface MessagesViewController ()

@end

@implementation MessagesViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}


#pragma mark - Conversation Handling

-(void)didBecomeActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the inactive to active state.
    // This will happen when the extension is about to present UI.
    
    // Use this method to configure the extension and restore previously stored state.
}

-(void)willResignActiveWithConversation:(MSConversation *)conversation {
    // Called when the extension is about to move from the active to inactive state.
    // This will happen when the user dissmises the extension, changes to a different
    // conversation or quits Messages.
    
    // Use this method to release shared resources, save user data, invalidate timers,
    // and store enough state information to restore your extension to its current state
    // in case it is terminated later.
}

-(void)didReceiveMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when a message arrives that was generated by another instance of this
    // extension on a remote device.
    
    // Use this method to trigger UI updates in response to the message.
}

-(void)didStartSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user taps the send button.
}

-(void)didCancelSendingMessage:(MSMessage *)message conversation:(MSConversation *)conversation {
    // Called when the user deletes the message without sending it.
    
    // Use this to clean up state related to the deleted message.
}

-(void)willTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    if(presentationStyle == MSMessagesAppPresentationStyleCompact){
        [self dismissViewControllerAnimated:YES completion:nil];
    }else if(presentationStyle == MSMessagesAppPresentationStyleExpanded){
        MDNewMoodViewController *VC = [self.storyboard instantiateViewControllerWithIdentifier:@"newMoodmonVC"];
        [self presentViewController:VC animated:YES completion:nil];
    }
}

-(void)didTransitionToPresentationStyle:(MSMessagesAppPresentationStyle)presentationStyle {
    
}

- (IBAction)buttonTouchUp:(id)sender {
    [self requestPresentationStyle:MSMessagesAppPresentationStyleExpanded];
}
@end
